; Listing generated by Microsoft (R) Optimizing Compiler Version 19.32.31329.0 

	TITLE	C:\Users\lsy01\OneDrive\바탕 화면\3-2_Study\인공지능\Source\VS2010\Buckland_Chapter7 to 10_Raven\Debug\BaseGameEntity.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

PUBLIC	?m_iNextValidID@BaseGameEntity@@0HA		; BaseGameEntity::m_iNextValidID
_BSS	SEGMENT
?m_iNextValidID@BaseGameEntity@@0HA DD 01H DUP (?)	; BaseGameEntity::m_iNextValidID
_BSS	ENDS
CONST	SEGMENT
$SG158115 DB	'<BaseGameEntity::SetID>: invalid ID', 00H
$SG162665 DB	'invalid argument', 00H
	ORG $+3
$SG158116 DB	'C', 00H, ':', 00H, '\', 00H, 'U', 00H, 's', 00H, 'e', 00H
	DB	'r', 00H, 's', 00H, '\', 00H, 'l', 00H, 's', 00H, 'y', 00H, '0'
	DB	00H, '1', 00H, '\', 00H, 'O', 00H, 'n', 00H, 'e', 00H, 'D', 00H
	DB	'r', 00H, 'i', 00H, 'v', 00H, 'e', 00H, '\', 00H, 014H, 0bcH, 0d5H
	DB	0d0H, ' ', 00H, 'T', 0d6H, 't', 0baH, '\', 00H, '3', 00H, '-', 00H
	DB	'2', 00H, '_', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'y'
	DB	00H, '\', 00H, 'x', 0c7H, 0f5H, 0acH, 0c0H, 0c9H, 0a5H, 0b2H, '\'
	DB	00H, 'S', 00H, 'o', 00H, 'u', 00H, 'r', 00H, 'c', 00H, 'e', 00H
	DB	'\', 00H, 'V', 00H, 'S', 00H, '2', 00H, '0', 00H, '1', 00H, '0'
	DB	00H, '\', 00H, 'C', 00H, 'o', 00H, 'm', 00H, 'm', 00H, 'o', 00H
	DB	'n', 00H, '\', 00H, 'G', 00H, 'a', 00H, 'm', 00H, 'e', 00H, '\'
	DB	00H, 'B', 00H, 'a', 00H, 's', 00H, 'e', 00H, 'G', 00H, 'a', 00H
	DB	'm', 00H, 'e', 00H, 'E', 00H, 'n', 00H, 't', 00H, 'i', 00H, 't'
	DB	00H, 'y', 00H, '.', 00H, 'c', 00H, 'p', 00H, 'p', 00H, 00H, 00H
$SG162666 DB	'%s', 00H
	ORG $+1
$SG158117 DB	'(', 00H, 'v', 00H, 'a', 00H, 'l', 00H, ' ', 00H, '>', 00H
	DB	'=', 00H, ' ', 00H, 'm', 00H, '_', 00H, 'i', 00H, 'N', 00H, 'e'
	DB	00H, 'x', 00H, 't', 00H, 'V', 00H, 'a', 00H, 'l', 00H, 'i', 00H
	DB	'd', 00H, 'I', 00H, 'D', 00H, ')', 00H, ' ', 00H, '&', 00H, '&'
	DB	00H, ' ', 00H, '"', 00H, '<', 00H, 'B', 00H, 'a', 00H, 's', 00H
	DB	'e', 00H, 'G', 00H, 'a', 00H, 'm', 00H, 'e', 00H, 'E', 00H, 'n'
	DB	00H, 't', 00H, 'i', 00H, 't', 00H, 'y', 00H, ':', 00H, ':', 00H
	DB	'S', 00H, 'e', 00H, 't', 00H, 'I', 00H, 'D', 00H, '>', 00H, ':'
	DB	00H, ' ', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'I', 00H, 'D', 00H, '"', 00H, 00H
	DB	00H
	ORG $+2
$SG162669 DB	00H, 00H
	ORG $+2
$SG162667 DB	'C:\Program Files\Microsoft Visual Studio\2022\Community\'
	DB	'VC\Tools\MSVC\14.32.31326\include\xmemory', 00H
	ORG $+6
$SG162668 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, '\', 00H, 'M', 00H, 'i', 00H
	DB	'c', 00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't'
	DB	00H, ' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H
	DB	'l', 00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i'
	DB	00H, 'o', 00H, '\', 00H, '2', 00H, '0', 00H, '2', 00H, '2', 00H
	DB	'\', 00H, 'C', 00H, 'o', 00H, 'm', 00H, 'm', 00H, 'u', 00H, 'n'
	DB	00H, 'i', 00H, 't', 00H, 'y', 00H, '\', 00H, 'V', 00H, 'C', 00H
	DB	'\', 00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\'
	DB	00H, 'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1', 00H
	DB	'4', 00H, '.', 00H, '3', 00H, '2', 00H, '.', 00H, '3', 00H, '1'
	DB	00H, '3', 00H, '2', 00H, '6', 00H, '\', 00H, 'i', 00H, 'n', 00H
	DB	'c', 00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x'
	DB	00H, 'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y', 00H
	DB	00H, 00H
$SG162670 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXI@Z		; __empty_global_delete
PUBLIC	??0Vector2D@@QAE@XZ				; Vector2D::Vector2D
PUBLIC	??0Vector2D@@QAE@NN@Z				; Vector2D::Vector2D
PUBLIC	?SetID@BaseGameEntity@@AAEXH@Z			; BaseGameEntity::SetID
PUBLIC	??0BaseGameEntity@@IAE@H@Z			; BaseGameEntity::BaseGameEntity
PUBLIC	??1BaseGameEntity@@UAE@XZ			; BaseGameEntity::~BaseGameEntity
PUBLIC	?Update@BaseGameEntity@@UAEXXZ			; BaseGameEntity::Update
PUBLIC	?HandleMessage@BaseGameEntity@@UAE_NABUTelegram@@@Z ; BaseGameEntity::HandleMessage
PUBLIC	?Write@BaseGameEntity@@UBEXAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z ; BaseGameEntity::Write
PUBLIC	?Read@BaseGameEntity@@UAEXAAV?$basic_ifstream@DU?$char_traits@D@std@@@std@@@Z ; BaseGameEntity::Read
PUBLIC	??_GBaseGameEntity@@UAEPAXI@Z			; BaseGameEntity::`scalar deleting destructor'
PUBLIC	??_7BaseGameEntity@@6B@				; BaseGameEntity::`vftable'
PUBLIC	??_R4BaseGameEntity@@6B@			; BaseGameEntity::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVBaseGameEntity@@@8			; BaseGameEntity `RTTI Type Descriptor'
PUBLIC	??_R3BaseGameEntity@@8				; BaseGameEntity::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2BaseGameEntity@@8				; BaseGameEntity::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@BaseGameEntity@@8			; BaseGameEntity::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	__real@3ff0000000000000
EXTRN	__purecall:PROC
EXTRN	??3@YAXPAXI@Z:PROC				; operator delete
EXTRN	__wassert:PROC
EXTRN	??_EBaseGameEntity@@UAEPAXI@Z:PROC		; BaseGameEntity::`vector deleting destructor'
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
EXTRN	__fltused:DWORD
;	COMDAT __real@3ff0000000000000
CONST	SEGMENT
__real@3ff0000000000000 DQ 03ff0000000000000r	; 1
CONST	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_R1A@?0A@EA@BaseGameEntity@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@BaseGameEntity@@8 DD FLAT:??_R0?AVBaseGameEntity@@@8 ; BaseGameEntity::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3BaseGameEntity@@8
rdata$r	ENDS
;	COMDAT ??_R2BaseGameEntity@@8
rdata$r	SEGMENT
??_R2BaseGameEntity@@8 DD FLAT:??_R1A@?0A@EA@BaseGameEntity@@8 ; BaseGameEntity::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3BaseGameEntity@@8
rdata$r	SEGMENT
??_R3BaseGameEntity@@8 DD 00H				; BaseGameEntity::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2BaseGameEntity@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVBaseGameEntity@@@8
data$rs	SEGMENT
??_R0?AVBaseGameEntity@@@8 DD FLAT:??_7type_info@@6B@	; BaseGameEntity `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVBaseGameEntity@@', 00H
data$rs	ENDS
;	COMDAT ??_R4BaseGameEntity@@6B@
rdata$r	SEGMENT
??_R4BaseGameEntity@@6B@ DD 00H				; BaseGameEntity::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVBaseGameEntity@@@8
	DD	FLAT:??_R3BaseGameEntity@@8
rdata$r	ENDS
;	COMDAT ??_7BaseGameEntity@@6B@
CONST	SEGMENT
??_7BaseGameEntity@@6B@ DD FLAT:??_R4BaseGameEntity@@6B@ ; BaseGameEntity::`vftable'
	DD	FLAT:??_EBaseGameEntity@@UAEPAXI@Z
	DD	FLAT:?Update@BaseGameEntity@@UAEXXZ
	DD	FLAT:__purecall
	DD	FLAT:?HandleMessage@BaseGameEntity@@UAE_NABUTelegram@@@Z
	DD	FLAT:?Write@BaseGameEntity@@UBEXAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z
	DD	FLAT:?Read@BaseGameEntity@@UAEXAAV?$basic_ifstream@DU?$char_traits@D@std@@@std@@@Z
CONST	ENDS
; Function compile flags: /Odtp /RTCsu
;	COMDAT ??_GBaseGameEntity@@UAEPAXI@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
___flags$ = 8						; size = 4
??_GBaseGameEntity@@UAEPAXI@Z PROC			; BaseGameEntity::`scalar deleting destructor', COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1BaseGameEntity@@UAE@XZ		; BaseGameEntity::~BaseGameEntity
	mov	eax, DWORD PTR ___flags$[ebp]
	and	eax, 1
	je	SHORT $LN2@scalar
	push	64					; 00000040H
	mov	ecx, DWORD PTR _this$[ebp]
	push	ecx
	call	??3@YAXPAXI@Z				; operator delete
	add	esp, 8
$LN2@scalar:
	mov	eax, DWORD PTR _this$[ebp]
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??_GBaseGameEntity@@UAEPAXI@Z ENDP			; BaseGameEntity::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File C:\Users\lsy01\OneDrive\바탕 화면\3-2_Study\인공지능\Source\VS2010\Common\Game\BaseGameEntity.h
;	COMDAT ?Read@BaseGameEntity@@UAEXAAV?$basic_ifstream@DU?$char_traits@D@std@@@std@@@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
_is$ = 8						; size = 4
?Read@BaseGameEntity@@UAEXAAV?$basic_ifstream@DU?$char_traits@D@std@@@std@@@Z PROC ; BaseGameEntity::Read, COMDAT
; _this$ = ecx

; 79   :   virtual void Read (std::ifstream& is){}

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	esp, ebp
	pop	ebp
	ret	4
?Read@BaseGameEntity@@UAEXAAV?$basic_ifstream@DU?$char_traits@D@std@@@std@@@Z ENDP ; BaseGameEntity::Read
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File C:\Users\lsy01\OneDrive\바탕 화면\3-2_Study\인공지능\Source\VS2010\Common\Game\BaseGameEntity.h
;	COMDAT ?Write@BaseGameEntity@@UBEXAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
_os$ = 8						; size = 4
?Write@BaseGameEntity@@UBEXAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z PROC ; BaseGameEntity::Write, COMDAT
; _this$ = ecx

; 78   :   virtual void Write(std::ostream&  os)const{}

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	esp, ebp
	pop	ebp
	ret	4
?Write@BaseGameEntity@@UBEXAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z ENDP ; BaseGameEntity::Write
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File C:\Users\lsy01\OneDrive\바탕 화면\3-2_Study\인공지능\Source\VS2010\Common\Game\BaseGameEntity.h
;	COMDAT ?HandleMessage@BaseGameEntity@@UAE_NABUTelegram@@@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
_msg$ = 8						; size = 4
?HandleMessage@BaseGameEntity@@UAE_NABUTelegram@@@Z PROC ; BaseGameEntity::HandleMessage, COMDAT
; _this$ = ecx

; 75   :   virtual bool HandleMessage(const Telegram& msg){return false;}

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	xor	al, al
	mov	esp, ebp
	pop	ebp
	ret	4
?HandleMessage@BaseGameEntity@@UAE_NABUTelegram@@@Z ENDP ; BaseGameEntity::HandleMessage
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File C:\Users\lsy01\OneDrive\바탕 화면\3-2_Study\인공지능\Source\VS2010\Common\Game\BaseGameEntity.h
;	COMDAT ?Update@BaseGameEntity@@UAEXXZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?Update@BaseGameEntity@@UAEXXZ PROC			; BaseGameEntity::Update, COMDAT
; _this$ = ecx

; 71   :   virtual void Update(){}; 

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	esp, ebp
	pop	ebp
	ret	0
?Update@BaseGameEntity@@UAEXXZ ENDP			; BaseGameEntity::Update
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File C:\Users\lsy01\OneDrive\바탕 화면\3-2_Study\인공지능\Source\VS2010\Common\Game\BaseGameEntity.h
;	COMDAT ??1BaseGameEntity@@UAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1BaseGameEntity@@UAE@XZ PROC				; BaseGameEntity::~BaseGameEntity, COMDAT
; _this$ = ecx

; 69   :   virtual ~BaseGameEntity(){}

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7BaseGameEntity@@6B@
	mov	esp, ebp
	pop	ebp
	ret	0
??1BaseGameEntity@@UAE@XZ ENDP				; BaseGameEntity::~BaseGameEntity
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File C:\Users\lsy01\OneDrive\바탕 화면\3-2_Study\인공지능\Source\VS2010\Common\Game\BaseGameEntity.cpp
_TEXT	SEGMENT
_this$ = -4						; size = 4
_ID$ = 8						; size = 4
??0BaseGameEntity@@IAE@H@Z PROC				; BaseGameEntity::BaseGameEntity
; _this$ = ecx

; 12   : {

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7BaseGameEntity@@6B@

; 10   :                                        m_iType(default_entity_type),

	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+12], -1

; 11   :                                        m_bTag(false)

	mov	edx, DWORD PTR _this$[ebp]
	mov	BYTE PTR [edx+16], 0

; 12   : {

	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 24					; 00000018H
	call	??0Vector2D@@QAE@XZ			; Vector2D::Vector2D

; 9    :                                        m_vScale(Vector2D(1.0,1.0)),

	sub	esp, 8
	movsd	xmm0, QWORD PTR __real@3ff0000000000000
	movsd	QWORD PTR [esp], xmm0
	sub	esp, 8
	movsd	xmm0, QWORD PTR __real@3ff0000000000000
	movsd	QWORD PTR [esp], xmm0
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 40					; 00000028H
	call	??0Vector2D@@QAE@NN@Z			; Vector2D::Vector2D

; 8    : BaseGameEntity::BaseGameEntity(int ID):m_dBoundingRadius(0.0),

	mov	eax, DWORD PTR _this$[ebp]
	xorps	xmm0, xmm0
	movsd	QWORD PTR [eax+56], xmm0

; 13   :   SetID(ID);

	mov	ecx, DWORD PTR _ID$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	?SetID@BaseGameEntity@@AAEXH@Z		; BaseGameEntity::SetID

; 14   : }

	mov	eax, DWORD PTR _this$[ebp]
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??0BaseGameEntity@@IAE@H@Z ENDP				; BaseGameEntity::BaseGameEntity
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File C:\Users\lsy01\OneDrive\바탕 화면\3-2_Study\인공지능\Source\VS2010\Common\Game\BaseGameEntity.cpp
_TEXT	SEGMENT
_this$ = -4						; size = 4
_val$ = 8						; size = 4
?SetID@BaseGameEntity@@AAEXH@Z PROC			; BaseGameEntity::SetID
; _this$ = ecx

; 24   : {

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx

; 25   :   //make sure the val is equal to or greater than the next available ID
; 26   :   assert ( (val >= m_iNextValidID) && "<BaseGameEntity::SetID>: invalid ID");

	mov	eax, DWORD PTR _val$[ebp]
	cmp	eax, DWORD PTR ?m_iNextValidID@BaseGameEntity@@0HA ; BaseGameEntity::m_iNextValidID
	jl	SHORT $LN3@SetID
	mov	ecx, OFFSET $SG158115
	test	ecx, ecx
	jne	SHORT $LN4@SetID
$LN3@SetID:
	push	26					; 0000001aH
	push	OFFSET $SG158116
	push	OFFSET $SG158117
	call	__wassert
	add	esp, 12					; 0000000cH
$LN4@SetID:

; 27   : 
; 28   :   m_ID = val;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _val$[ebp]
	mov	DWORD PTR [eax+8], ecx

; 29   :     
; 30   :   m_iNextValidID = m_ID + 1;

	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+8]
	add	eax, 1
	mov	DWORD PTR ?m_iNextValidID@BaseGameEntity@@0HA, eax ; BaseGameEntity::m_iNextValidID

; 31   : }

	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?SetID@BaseGameEntity@@AAEXH@Z ENDP			; BaseGameEntity::SetID
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File C:\Users\lsy01\OneDrive\바탕 화면\3-2_Study\인공지능\Source\VS2010\Common\2D\Vector2D.h
;	COMDAT ??0Vector2D@@QAE@NN@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
_a$ = 8							; size = 8
_b$ = 16						; size = 8
??0Vector2D@@QAE@NN@Z PROC				; Vector2D::Vector2D, COMDAT
; _this$ = ecx

; 25   :   Vector2D(double a, double b):x(a),y(b){}

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	movsd	xmm0, QWORD PTR _a$[ebp]
	movsd	QWORD PTR [eax], xmm0
	mov	ecx, DWORD PTR _this$[ebp]
	movsd	xmm0, QWORD PTR _b$[ebp]
	movsd	QWORD PTR [ecx+8], xmm0
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	16					; 00000010H
??0Vector2D@@QAE@NN@Z ENDP				; Vector2D::Vector2D
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File C:\Users\lsy01\OneDrive\바탕 화면\3-2_Study\인공지능\Source\VS2010\Common\2D\Vector2D.h
;	COMDAT ??0Vector2D@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0Vector2D@@QAE@XZ PROC				; Vector2D::Vector2D, COMDAT
; _this$ = ecx

; 24   :   Vector2D():x(0.0),y(0.0){}

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	xorps	xmm0, xmm0
	movsd	QWORD PTR [eax], xmm0
	mov	ecx, DWORD PTR _this$[ebp]
	xorps	xmm0, xmm0
	movsd	QWORD PTR [ecx+8], xmm0
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0Vector2D@@QAE@XZ ENDP				; Vector2D::Vector2D
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File C:\Users\lsy01\OneDrive\바탕 화면\3-2_Study\인공지능\Source\VS2010\Common\Game\BaseGameEntity.cpp
;	COMDAT ?__empty_global_delete@@YAXPAXI@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXI@Z PROC			; __empty_global_delete, COMDAT

	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAXI@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu
; File C:\Users\lsy01\OneDrive\바탕 화면\3-2_Study\인공지능\Source\VS2010\Common\Game\BaseGameEntity.cpp
;	COMDAT ?__empty_global_delete@@YAXPAX@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?__empty_global_delete@@YAXPAX@Z PROC			; __empty_global_delete, COMDAT

	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
